version: '3.8'

services:

  question-service:
    build:
      context: ./backend/questions
    restart: always
    env_file:
      - ./backend/questions/.env
    ports:
      - ${QUESTION_PORT}:${QUESTION_PORT}
    networks:
      - default

  user-service:
    build:
      context: ./backend/users
    restart: always
    env_file:
      - ./backend/users/.env
    ports:
      - ${USER_PORT}:${USER_PORT}
    networks:
      - default

  frontend:
    build:
      context: ./frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - default
    depends_on:
      - user-service
      - question-service

networks:
  default:
    name: peerprep
    driver: bridge
