export enum ProgrammingLanguages {
  C = 'C',
  Cpp = 'Cpp',
  Java = 'Java',
  Python = 'Python',
  Javascript = 'Javascript',
  Go = 'Go',
  Ruby = 'Ruby'
}

export enum Difficulties {
  Easy = 'Easy',
  Medium = 'Medium',
  Hard = 'Hard'
}

export const Categories = {
  1: 'string',
  2: 'string-matching',
  3: 'stack',
  4: 'two-pointers',
  5: 'array',
  6: 'linked-list',
  7: 'trie',
  8: 'sliding-window',
  9: 'backtracking',
  10: 'recursion',
  11: 'math',
  12: 'binary-search',
  13: 'bit-manipulation',
  14: 'greedy',
  15: 'sorting',
  16: 'merge-sort',
  17: 'hash-table',
  18: 'divide-and-conquer',
  19: 'dynamic-programming',
  20: 'heap-priority-queue',
  21: 'matrix',
  22: 'monotonic-stack',
  23: 'simulation',
  24: 'combinatorics',
  25: 'memoization',
  26: 'depth-first-search',
  27: 'binary-tree',
  28: 'tree',
  29: 'breadth-first-search',
  30: 'binary-search-tree',
  31: 'union-find',
  32: 'graph',
  33: 'geometry',
  34: 'design',
  35: 'doubly-linked-list',
  36: 'interactive',
  37: 'counting',
  38: 'radix-sort',
  39: 'data-stream',
  40: 'bucket-sort',
  41: 'iterator',
  42: 'rolling-hash',
  43: 'database',
  44: 'shell',
  45: 'hash-function',
  46: 'enumeration',
  47: 'topological-sort',
  48: 'prefix-sum',
  49: 'quickselect',
  50: 'binary-indexed-tree',
  51: 'segment-tree',
  52: 'line-sweep',
  53: 'queue',
  54: 'ordered-set',
  55: 'game-theory',
  56: 'counting-sort',
  57: 'monotonic-queue',
  58: 'number-theory',
  59: 'brainteaser',
  60: 'shortest-path',
  61: 'reservoir-sampling',
  62: 'randomized',
  63: 'rejection-sampling',
  64: 'eulerian-circuit',
  65: 'suffix-array',
  66: 'probability-and-statistics',
  67: 'bitmask',
  68: 'biconnected-component',
  69: 'concurrency',
  70: 'minimum-spanning-tree',
  71: 'strongly-connected-component'
} as const;

export type CategoryName = keyof typeof Categories;
export type CategoryId = (typeof Categories)[CategoryName];
