export enum ProgrammingLanguages {
  C = 'C',
  Cpp = 'Cpp',
  Java = 'Java',
  Python = 'Python',
  Javascript = 'Javascript',
  Go = 'Go',
  Ruby = 'Ruby'
}

export enum Difficulties {
  Easy = 'Easy',
  Medium = 'Medium',
  Hard = 'Hard'
}

export enum Category {
  'graph',
  'randomized',
  'enumeration',
  'two-pointers',
  'binary-search',
  'concurrency',
  'reservoir-sampling',
  'sliding-window',
  'string',
  'monotonic-stack',
  'memoization',
  'binary-indexed-tree',
  'eulerian-circuit',
  'breadth-first-search',
  'binary-tree',
  'trie',
  'strongly-connected-component',
  'greedy',
  'geometry',
  'hash-table',
  'dynamic-programming',
  'sorting',
  'string-matching',
  'interactive',
  'probability-and-statistics',
  'simulation',
  'brainteaser',
  'recursion',
  'queue',
  'stack',
  'prefix-sum',
  'tree',
  'counting-sort',
  'rejection-sampling',
  'suffix-array',
  'divide-and-conquer',
  'combinatorics',
  'doubly-linked-list',
  'radix-sort',
  'number-theory',
  'merge-sort',
  'line-sweep',
  'union-find',
  'shortest-path',
  'bitmask',
  'biconnected-component',
  'binary-search-tree',
  'rolling-hash',
  'counting',
  'database',
  'game-theory',
  'backtracking',
  'iterator',
  'array',
  'heap-priority-queue',
  'matrix',
  'hash-function',
  'bit-manipulation',
  'segment-tree',
  'bucket-sort',
  'data-stream',
  'shell',
  'minimum-spanning-tree',
  'topological-sort',
  'depth-first-search',
  'quickselect',
  'monotonic-queue',
  'design',
  'math',
  'linked-list',
  'ordered-set'
}
